### ISSUE TITLE
Linker command failed

### ISSUE THREAD

**Issue by LegoTechApps** [dkhamsing/DKImageBrowser#26]
after dragging the folder & Build
"Linker command failed"
![screen shot 2017-04-27 at 3 23 26 pm](https://cloud.githubusercontent.com/assets/18591535/25483197/88262aba-2b5d-11e7-8ddc-2beb96c33a25.png)

- all files in target
- no multiple files in compiler
- (running on device)
how to fix it?

**Comment by dkhamsing** [comment]
thx for the report, will try to look into this

**Comment by dkhamsing** [comment]
Looks like the enum declaration should be `static`, pushed the changes https://github.com/dkhamsing/DKImageBrowser/commit/d6f422fd3a37afdf5cf2d01e2e4497df798bdf72

**Comment by dkhamsing** [comment]
Can you get the latest version and update

**Comment by LegoTechApps** [comment]
running √
