### ISSUE TITLE
how to show the specified position image?

### ISSUE THREAD

**Issue by jbasttdi** [dkhamsing/DKImageBrowser#5]
thanks for your great work.
Now i want to show the specified position image.how can i do it?
source: imgs:[a.jpg,b.jgp,c.jpg]
now i want to show the b.jpg on the initialized page.

**Comment by dkhamsing** [comment]
At the moment it is not possible, but let me see if it can be added

**Comment by dkhamsing** [comment]
@jbasttdi added a property for starting index `DKStartIndex`, this is on the 0.1.3 tag/release

**Comment by jbasttdi** [comment]
thanks.
